services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules # Skryje node_modules v hostu (aby se nepletly)
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "start:dev", "--", "--host", "0.0.0.0" ]
  s2t:
    build:
      context: ./s2t
      dockerfile: Dockerfile
    container_name: S2T
    depends_on:
      - server
    ports:
      - "3010:3010"
    volumes:
      - ./s2t:/app
    command: [ "node", "server" ]
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - server
      - s2t
    ports:
      - "8080:3006"
    volumes:
      - ./web:/app
      - /app/node_modules # Skryje node_modules v hostu (aby se nepletly)
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]